SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

CREATE DATABASE IF NOT EXISTS `ed102g3` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; USE
    `ed102g3`;
CREATE TABLE IF NOT EXISTS `POSTCARD_MATERIAL`(
    `POS_MAT_NO` INT NOT NULL AUTO_INCREMENT,
    `POS_MAT_NAME` VARCHAR(10) NOT NULL,
    `POS_MAT_PIC` VARCHAR(255) NOT NULL,
    `POS_MAT_USE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`POS_MAT_NO`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ADMINISTRATOR`(
    `AD_NO` INT NOT NULL AUTO_INCREMENT,
    `AD_NAME` VARCHAR(20) NOT NULL,
    `AD_ACCOUNT` VARCHAR(10) NOT NULL UNIQUE,
    `AD_PASSWORD` VARCHAR(10) NOT NULL,
    `AD_MAT_USE` BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(`AD_NO`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `MEMBER`(
    `MEM_NO` INT NOT NULL AUTO_INCREMENT,
    `MEM_NAME` VARCHAR(20) NOT NULL,
    `MEM_CODE` VARCHAR(20) NOT NULL,
    `MEM_PIC` VARCHAR(255) DEFAULT './img/member/member_Img/member01.svg',
    `MEM_TEL` VARCHAR(10) DEFAULT '©|¥¼¿é¤J',
    `MEM_EMAIL` VARCHAR(50) NOT NULL UNIQUE,
    `MEM_USE` BOOLEAN DEFAULT 0,
    PRIMARY KEY(`MEM_NO`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `POSTCARD`(
    `POS_NO` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `POS_PIC` VARCHAR(255) NOT NULL,
    `POS_PIC_BACK` VARCHAR(255) NOT NULL,
    `POS_CRE_DATE` DATE NOT NULL,
    `POS_SEN_DATE` DATE NOT NULL,
    PRIMARY KEY(`POS_NO`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `INDUSTRY_CLASS`(
    `IND_NO` CHAR(1) NOT NULL,
    `IND_CLASS` VARCHAR(10) NOT NULL,
    `IND_INFO` VARCHAR(4096) NOT NULL,
    `IND_COLOR` VARCHAR(10) NOT NULL,
    PRIMARY KEY(`IND_NO`)
) ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `INDUSTRY_INTRODUCE`(
    `IND_INT_NO` INT NOT NULL AUTO_INCREMENT,
    `IND_INT_NAME` VARCHAR(50) NOT NULL,
    `IND_INT_INTRO` VARCHAR(4096) NOT NULL,
    `IND_INT_PICTURE` VARCHAR(255) NOT NULL,
    `IND_NO` CHAR(1) NOT NULL,
    `INT_INT_CONTENT` VARCHAR(4096) NOT NULL,
    `IND_INT_SKILL` VARCHAR(4096) NOT NULL,
    PRIMARY KEY(`IND_INT_NO`),
    FOREIGN KEY(IND_NO) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `INDUSTRY_SALARY`(
    `IND_SAL_NO` INT NOT NULL AUTO_INCREMENT,
    `IND_SAL_STEP_DISTANCE` VARCHAR(50) NOT NULL,
    `IND_SAL_LOW` INT NOT NULL,
    `IND_SAL_HIGH` INT NOT NULL,
    `IND_INT_NO` INT NOT NULL,
    PRIMARY KEY(`IND_SAL_NO`),
    FOREIGN KEY(IND_INT_NO) REFERENCES INDUSTRY_INTRODUCE(IND_INT_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `QUIZ`(
    `QUIZ_NO` INT NOT NULL AUTO_INCREMENT,
    `QUIZ_CON` VARCHAR(255) NOT NULL,
    `QUIZ_PIC_ONE` VARCHAR(255) NOT NULL,
    `QUIZ_PIC_TWO` VARCHAR(255) NOT NULL,
    `QUIZ_SEL_ONE_CONTENT` VARCHAR(255) NOT NULL,
    `QUIZ_SEL_ONE_CLASS` CHAR(1) NOT NULL,
    `QUIZ_SEL_TWO_CONTENT` VARCHAR(255) NOT NULL,
    `QUIZ_SEL_TWO_CLASS` CHAR(1) NOT NULL,
    `QUIZ_USE` BOOLEAN DEFAULT 1,
    PRIMARY KEY(`QUIZ_NO`),
    FOREIGN KEY(QUIZ_SEL_ONE_CLASS) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(QUIZ_SEL_TWO_CLASS) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `QUIZ_RESULT_ANALYSIS`(
    `QUIZ_RES_NO` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `QUIZ_RES_TYPE_R` INT NOT NULL,
    `QUIZ_RES_TYPE_I` INT NOT NULL,
    `QUIZ_RES_TYPE_A` INT NOT NULL,
    `QUIZ_RES_TYPE_S` INT NOT NULL,
    `QUIZ_RES_TYPE_E` INT NOT NULL,
    `QUIZ_RES_TYPE_C` INT NOT NULL,
   	`QUIZ_RES_DATE` DATE NOT NULL,
    `QUIZ_RES_FIT_TYPE` CHAR(1) NOT NULL,
    PRIMARY KEY(`QUIZ_RES_NO`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(QUIZ_RES_FIT_TYPE) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `SKILL_CLASS`(
    `SKI_NO` INT NOT NULL AUTO_INCREMENT,
    `SKI_NAME` VARCHAR(100) NOT NULL,
    `IND_NO` CHAR(1) NOT NULL,
    `SKI_BUY_NUM` INT NOT NULL DEFAULT 0,
    `SKI_PRICE` INT NOT NULL,
    `SKI_TIME` VARCHAR(20) NOT NULL,
    `SKI_INTRO` VARCHAR(4096) NOT NULL,
    `SKI_HARVEST` VARCHAR(255) NOT NULL,
    `SKI_LINK` VARCHAR(255) NOT NULL,
    `SKI_IMG` VARCHAR(255) NOT NULL,
    `SKI_TEC_IMG` VARCHAR(255) NOT NULL,
    `SKI_TEC_NAME` VARCHAR(50) NOT NULL,
    `SKI_TEC_INTRO` VARCHAR(4096) NOT NULL,
    `SKI_OUTLINE` VARCHAR(255) NOT NULL,
    `SKI_STUD` VARCHAR(100) NOT NULL,
    `SKI_HIDDEN` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`SKI_NO`),
    FOREIGN KEY(IND_NO) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `SKILL_COLLECT`(
    `SKI_COL` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `SKI_NO` INT NOT NULL,
    `SKI_COL_STATE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`SKI_COL`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(SKI_NO) REFERENCES SKILL_CLASS(SKI_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `FORUM`(
    `FOR_NO` INT NOT NULL AUTO_INCREMENT,
    `FOR_NAME` VARCHAR(50) NOT NULL,
    `IND_NO` CHAR(1) NOT NULL,
    `FOR_LOW_LIMIT` INT NOT NULL,
    `FOR_UPP_LIMIT` INT NOT NULL,
    `FOR_STA_DATE` DATE NOT NULL,
    `FOR_BUY_NUM` INT NOT NULL,
    `FOR_PRICE` INT NOT NULL,
    `FOR_HIDDEN` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`FOR_NO`),
    FOREIGN KEY(IND_NO) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `FORUM_COLLECT`(
    `FOR_COL` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `FOR_NO` INT NOT NULL,
    PRIMARY KEY(`FOR_COL`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(FOR_NO) REFERENCES FORUM(FOR_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `FORUM_SIGN_UP`(
    `FOR_SIG_UP` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `FOR_NO` INT NOT NULL,
    PRIMARY KEY(`FOR_SIG_UP`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(FOR_NO) REFERENCES FORUM(FOR_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ORDER_MEM`(
    `ORD_NO` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `ORD_DISCOUNT` CHAR(1) NOT NULL DEFAULT 0,
    `ORD_AMOUNT` INT NOT NULL,
    `ORD_PAY` VARCHAR(50) NOT NULL,
    `ORD_DATE` DATETIME NOT NULL,
    PRIMARY KEY(`ORD_NO`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ORDER_DETAIL`(
    `ORD_DET_NO` INT NOT NULL AUTO_INCREMENT,
    `ORD_NO` INT NOT NULL,
    `SKI_NO` INT NOT NULL,
    `ORD_DET_PRICE` INT NOT NULL,
    PRIMARY KEY(`ORD_DET_NO`),
    FOREIGN KEY(ORD_NO) REFERENCES ORDER_MEM(ORD_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(SKI_NO) REFERENCES SKILL_CLASS(SKI_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `DISCUSS_AREA`(
    `DIS_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_NAME` VARCHAR(50) NOT NULL,
    `DIS_CLASS` VARCHAR(20) NOT NULL,
    `IND_NO` CHAR(1) NOT NULL,
    `DIS_CONTENT` VARCHAR(4096) NOT NULL,
    `DIS_DATE` DATE NOT NULL,
    `DIS_COL_NUM` INT NOT NULL DEFAULT 0,
    `DIS_LIK_NUM` INT  NOT NULL DEFAULT 0,
    `MEM_NO` INT NOT NULL,
    `DIS_REP_NUM` INT NOT NULL DEFAULT 0,
    `DIS_HIDDEN` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`DIS_NO`),
    FOREIGN KEY(IND_NO) REFERENCES INDUSTRY_CLASS(IND_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ARTICLE_LIKE`(
    `ART_LIK_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `ART_LIK_STATE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`ART_LIK_NO`),
    FOREIGN KEY(DIS_NO) REFERENCES DISCUSS_AREA(DIS_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ARTICLE_REPORT`(
    `ART_REP_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `ART_REP_CONTENT` VARCHAR(255) NOT NULL,
    `ART_REP_PASS` INT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY(`ART_REP_NO`),
    FOREIGN KEY(DIS_NO) REFERENCES DISCUSS_AREA(DIS_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ARTICLE_COLLECT`(
    `ART_COL_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `ART_COL_STATE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`ART_COL_NO`),
    FOREIGN KEY(DIS_NO) REFERENCES DISCUSS_AREA(DIS_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `DISCUSS_MESSAGE`(
    `DIS_MES_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `DIS_MES_CONTENT` VARCHAR(4096) NOT NULL,
    `DIS_MES_DATE` DATE NOT NULL,
    `DIS_MES_LIK_NUM` INT NOT NULL DEFAULT 0,
    `DIS_MES_REP_NUM` INT NOT NULL DEFAULT 0,
    `DIS_MES_HIDDEN` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`DIS_MES_NO`),
    FOREIGN KEY(DIS_NO) REFERENCES DISCUSS_AREA(DIS_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `MESSAGE_LIKE`(
    `MES_LIK_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_MES_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `MES_LIK_STATE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`MES_LIK_NO`),
    FOREIGN KEY(DIS_MES_NO) REFERENCES DISCUSS_MESSAGE(DIS_MES_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `MESSAGE_REPORT`(
    `MES_REP_NO` INT NOT NULL AUTO_INCREMENT,
    `DIS_MES_NO` INT NOT NULL,
    `MEM_NO` INT NOT NULL,
    `MES_REP_CONTENT` VARCHAR(255) NOT NULL,
    `MES_REP_PASS` INT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY(`MES_REP_NO`),
    FOREIGN KEY(DIS_MES_NO) REFERENCES DISCUSS_MESSAGE(DIS_MES_NO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `MESSAGE`(
    `MES_NO` INT NOT NULL AUTO_INCREMENT,
    `MEM_NO` INT NOT NULL,
    `MES_TITLE` VARCHAR(255) NOT NULL,
    `MES_CONTENT` VARCHAR(1024) NOT NULL,
    `MES_DATE` DATE NOT NULL,
    `MES_READ` BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(`MES_NO`),
    FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `ANNOUNCEMENT`(
    `ANN_NO` INT NOT NULL AUTO_INCREMENT,
    `ANN_CONTENT` VARCHAR(50) NOT NULL,
    `ANN_DATE` DATE NOT NULL,
    `ANN_USE` BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY(`ANN_NO`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 AUTO_INCREMENT=1;